version: '3'
services:
  backend:
    build:
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ${PWD}/backend/src:/app/backend/src

  frontend:
    build:
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ${PWD}/frontend/src:/app/frontend/src
    depends_on:
      - backend
